networks:
    backend:
        driver: bridge
    proxy:
        external: true

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        image: frutymax_app:latest
        env_file:
            - .env
        restart: unless-stopped
        expose:
            - "9000"
        networks:
            - proxy
            - backend
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.exloz.rule=Host(`api.frutymax.exloz.site`)"
            - "traefik.http.routers.exloz.entrypoints=websecure"
            - "traefik.http.routers.exloz.tls.certresolver=le"
            - "traefik.http.services.exloz.loadbalancer.server.port=9000"
    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql:Z
        networks:
            - backend

volumes:
    mysql_data:
        driver: local
